package com.oculogx.terminal;

import com.google.android.glass.media.Sounds;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;

import android.app.Activity;
import android.content.Context;
import android.media.AudioManager;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;
import android.widget.AdapterView;
import android.widget.EditText;

import java.util.ArrayList;

/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 *
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */public class MainActivity extends Activity {

//    /**
//     * {@link CardScrollView} to use as the main content view.
//     */
//    private CardScrollView mCardScroller;

//    /**
//     * "Hello World!" {@link View} generated by {@link #buildView()}.
//     */
//    private View mView;

    private static final String TAG = "MainActivity";

//    @Override
//    public boolean onKeyDown(int keycode, KeyEvent event){
//        Log.d(TAG, "Larry is fun");
//        return true;
//
//
//    }

//    @Override
//    public boolean onKeyDown(int keycode, KeyEvent event){
//        if (keycode == KeyEvent.KEYCODE_DPAD_CENTER) {
//            EditText barcodeInput = (EditText) findViewById(R.id.barcodeInput);
//            barcodeInput.setText("Touched!");
//            Log.d(TAG, "Touched");
//            return true;
//        }
//
//        return super.onKeyDown(keycode, event);
//    }

    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);
        setContentView(R.layout.terminal);

//        mView = buildView();

        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);

        final EditText barcodeInput = (EditText) findViewById(R.id.terminal_edittext);
        barcodeInput.requestFocus();

        barcodeInput.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
            }

            @Override
            public void afterTextChanged(Editable s) {
                playSound();
            }
        });

    }

    @Override
    protected void onResume() {
        super.onResume();
//        mCardScroller.activate();

    }

    @Override
    protected void onPause() {
//        mCardScroller.deactivate();
        super.onPause();
    }

    protected void playSound(){
        AudioManager audio = (AudioManager) this.getSystemService(Context.AUDIO_SERVICE);
        audio.playSoundEffect(Sounds.SUCCESS);
    }

//    /**
//     * Builds a Glass styled "Hello World!" view using the {@link CardBuilder} class.
//     */
//    private View buildView() {
//        CardBuilder card = new CardBuilder(this, CardBuilder.Layout.EMBED_INSIDE)
//                .setEmbeddedLayout(R.layout.custom_ui)
//                .setFootnote("OGP Demo")
//                .setTimestamp("today");
//
//
//        return card.getView();
//    }

}
